export class Pedido {
  constructor(
    public id: number,
    public latitud: number,
    public longitud: number,
    public id_cliente: string,
    public id_conductor: string,
    public total: string,
    public estadoEliminado: string,
    public id_estado: string,
    public nit: string,
    public razonSocial: string,
    public id_comercio: string,
    public nota: string,
    public created_at: string,
    public token: string,
    public pNombre: string,
    public telefono: string,
    public nombreCompercio: string,
    public telefonoComercio: string,
    public delivery: string,
    public comerciolatitud: number,
    public comerciolonitud: number,
    public tiempoDelivery: string,
    public estado: string,
    public conductor: string,
    public conductorTelefono: string,
    public conductorFoto: string,
    public conductorTipoVehiculo: string,
    public cliente: string,
    public fotoComercio: string,
    public tokenComercio: string,
    public pedidoDelivery: string,
    public pApellido: string,
    public tipoVehiculo: string,
    public fotoVehiculo: string
  ) {}
}
